POST  "https://hoblist.com/movielist?category=movies&language=kannada&genre=all&sort=voting"
//Content-Type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDg5NGQxYzU3NDI1NDA1ZWM4ZjhkNmQiLCJpYXQiOjE2MTk2MTA5MjZ9.FgOgAufnwq1UT7yWNyi0IL9WgESYnSiadyayEGl9M7Q


